---
driver:
  name: hetznercloud
lint: |
  set -e
  yamllint .
platforms:
  - name: instance
    server_type: cx11
    image: debian-10
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        foo: bar
  lint: |
    set -e
    ansible-lint
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
