---
- name: Verify OpenJDK installation and configuration
  hosts: all
  tasks:
    - name: Get java version
      command: java --version
      register: java_version_result
    - name: Verify java version
      assert:
        that:
          - "'openjdk 11' in java_version_result.stdout"
